/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ErrorResponse,
  GetProductsParams,
  MenuItem,
  Product,
  ProductInput,
  ProductListResponse,
  StockSearchCondition
} from '../types/api';

import { customAxiosInstance } from '../plugins/axios';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary メインメニュー取得
 */
export const getMenu = (

 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {


      return customAxiosInstance<MenuItem[]>(
      {url: `/menu`, method: 'GET', signal
    },
      options);
    }




export const getGetMenuQueryKey = () => {
    return [
    'menu'
    ] as const;
    }


export const getGetMenuQueryOptions = <TData = Awaited<ReturnType<typeof getMenu>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetMenuQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenu>>> = ({ signal }) => getMenu(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>
}

export type GetMenuQueryResult = NonNullable<Awaited<ReturnType<typeof getMenu>>>
export type GetMenuQueryError = unknown


/**
 * @summary メインメニュー取得
 */

export function useGetMenu<TData = Awaited<ReturnType<typeof getMenu>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenu>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMenuQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







/**
 * @summary 商品一覧取得
 */
export const getProducts = (
    params?: MaybeRef<GetProductsParams>,
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      params = unref(params);

      return customAxiosInstance<ProductListResponse>(
      {url: `/products`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }




export const getGetProductsQueryKey = (params?: MaybeRef<GetProductsParams>,) => {
    return [
    'products', ...(params ? [params] : [])
    ] as const;
    }


export const getGetProductsQueryOptions = <TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(params?: MaybeRef<GetProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetProductsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({ signal }) => getProducts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>
}

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>
export type GetProductsQueryError = unknown


/**
 * @summary 商品一覧取得
 */

export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: MaybeRef<GetProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







/**
 * @summary 商品登録
 */
export const postProduct = (
    productInput: MaybeRef<ProductInput>,
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      productInput = unref(productInput);

      return customAxiosInstance<Product>(
      {url: `/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productInput, signal
    },
      options);
    }



export const getPostProductMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProduct>>, TError,{data: ProductInput}, TContext>, request?: SecondParameter<typeof customAxiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postProduct>>, TError,{data: ProductInput}, TContext> => {

const mutationKey = ['postProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProduct>>, {data: ProductInput}> = (props) => {
          const {data} = props ?? {};

          return  postProduct(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostProductMutationResult = NonNullable<Awaited<ReturnType<typeof postProduct>>>
    export type PostProductMutationBody = ProductInput
    export type PostProductMutationError = ErrorResponse

    /**
 * @summary 商品登録
 */
export const usePostProduct = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProduct>>, TError,{data: ProductInput}, TContext>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof postProduct>>,
        TError,
        {data: ProductInput},
        TContext
      > => {
      return useMutation(getPostProductMutationOptions(options), queryClient);
    }

/**
 * @summary 在庫検索（在庫検索画面専用の検索条件で商品を検索）
 */
export const searchStockProducts = (
    stockSearchCondition: MaybeRef<StockSearchCondition>,
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      stockSearchCondition = unref(stockSearchCondition);

      return customAxiosInstance<ProductListResponse>(
      {url: `/products/stock-search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stockSearchCondition, signal
    },
      options);
    }



export const getSearchStockProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchStockProducts>>, TError,{data: StockSearchCondition}, TContext>, request?: SecondParameter<typeof customAxiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof searchStockProducts>>, TError,{data: StockSearchCondition}, TContext> => {

const mutationKey = ['searchStockProducts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof searchStockProducts>>, {data: StockSearchCondition}> = (props) => {
          const {data} = props ?? {};

          return  searchStockProducts(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SearchStockProductsMutationResult = NonNullable<Awaited<ReturnType<typeof searchStockProducts>>>
    export type SearchStockProductsMutationBody = StockSearchCondition
    export type SearchStockProductsMutationError = unknown

    /**
 * @summary 在庫検索（在庫検索画面専用の検索条件で商品を検索）
 */
export const useSearchStockProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchStockProducts>>, TError,{data: StockSearchCondition}, TContext>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof searchStockProducts>>,
        TError,
        {data: StockSearchCondition},
        TContext
      > => {
      return useMutation(getSearchStockProductsMutationOptions(options), queryClient);
    }

/**
 * @summary 商品詳細取得
 */
export const getProductById = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      id = unref(id);

      return customAxiosInstance<Product>(
      {url: `/products/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetProductByIdQueryKey = (id: MaybeRef<number>,) => {
    return [
    'products',id
    ] as const;
    }


export const getGetProductByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductById>>, TError = ErrorResponse>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetProductByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductById>>> = ({ signal }) => getProductById(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: computed(() => unref(id) !== null && unref(id) !== undefined), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>
}

export type GetProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>
export type GetProductByIdQueryError = ErrorResponse


/**
 * @summary 商品詳細取得
 */

export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = ErrorResponse>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
