/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary メインメニュー取得
 */
export const GetMenuResponseItem = zod.object({
  "id": zod.string(),
  "label": zod.string(),
  "icon": zod.string(),
  "children": zod.array(zod.object({
  "label": zod.string(),
  "to": zod.string(),
  "icon": zod.string().optional()
}))
})
export const GetMenuResponse = zod.array(GetMenuResponseItem)


/**
 * @summary 商品一覧取得
 */
export const getProductsQueryPageDefault = 1;

export const getProductsQueryPageSizeDefault = 5;
export const getProductsQueryPageSizeMax = 100;



export const GetProductsQueryParams = zod.object({
  "q": zod.string().optional().describe('キーワード検索（name・description を対象）'),
  "category": zod.enum(['食品', '電子機器', 'ファッション', '家具', 'スポーツ']).optional().describe('カテゴリフィルタ'),
  "inStock": zod.boolean().optional().describe('在庫ありのみ'),
  "page": zod.number().min(1).default(getProductsQueryPageDefault).describe('ページ番号（1始まり）'),
  "pageSize": zod.number().min(1).max(getProductsQueryPageSizeMax).default(getProductsQueryPageSizeDefault).describe('1ページあたりの件数')
})

export const getProductsResponseItemsItemRatingMin = 0;
export const getProductsResponseItemsItemRatingMax = 5;

export const getProductsResponseItemsItemReviewsItemRatingMax = 5;



export const GetProductsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "category": zod.enum(['食品', '電子機器', 'ファッション', '家具', 'スポーツ']),
  "price": zod.number().describe('価格（円）'),
  "inStock": zod.boolean(),
  "description": zod.string(),
  "rating": zod.number().min(getProductsResponseItemsItemRatingMin).max(getProductsResponseItemsItemRatingMax),
  "reviews": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.string(),
  "rating": zod.number().min(1).max(getProductsResponseItemsItemReviewsItemRatingMax),
  "comment": zod.string()
}))
})),
  "total": zod.number().describe('フィルタ後の総件数'),
  "page": zod.number(),
  "pageSize": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary 商品登録
 */
export const PostProductBody = zod.object({
  "name": zod.string(),
  "category": zod.enum(['食品', '電子機器', 'ファッション', '家具', 'スポーツ']),
  "price": zod.number().describe('価格（円）'),
  "inStock": zod.boolean(),
  "description": zod.string()
})

export const PostProductResponse = zod.void()


/**
 * @summary 在庫検索（在庫検索画面専用の検索条件で商品を検索）
 */
export const SearchStockProductsBody = zod.object({
  "keywords": zod.array(zod.string()).optional().describe('キーワード（複数指定時は OR。name・description を対象）'),
  "categories": zod.array(zod.enum(['食品', '電子機器', 'ファッション', '家具', 'スポーツ'])).optional().describe('カテゴリ（複数指定時は OR）'),
  "inStockOnly": zod.boolean().optional().describe('在庫ありのみに絞り込む')
}).describe('在庫検索画面専用の検索条件（画面固有オブジェクトのお手本。プロパティ構成は画面ごとに自由に定義する）')

export const searchStockProductsResponseItemsItemRatingMin = 0;
export const searchStockProductsResponseItemsItemRatingMax = 5;

export const searchStockProductsResponseItemsItemReviewsItemRatingMax = 5;



export const SearchStockProductsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "category": zod.enum(['食品', '電子機器', 'ファッション', '家具', 'スポーツ']),
  "price": zod.number().describe('価格（円）'),
  "inStock": zod.boolean(),
  "description": zod.string(),
  "rating": zod.number().min(searchStockProductsResponseItemsItemRatingMin).max(searchStockProductsResponseItemsItemRatingMax),
  "reviews": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.string(),
  "rating": zod.number().min(1).max(searchStockProductsResponseItemsItemReviewsItemRatingMax),
  "comment": zod.string()
}))
})),
  "total": zod.number().describe('フィルタ後の総件数'),
  "page": zod.number(),
  "pageSize": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary 商品詳細取得
 */
export const GetProductByIdParams = zod.object({
  "id": zod.number()
})

export const getProductByIdResponseRatingMin = 0;
export const getProductByIdResponseRatingMax = 5;

export const getProductByIdResponseReviewsItemRatingMax = 5;



export const GetProductByIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "category": zod.enum(['食品', '電子機器', 'ファッション', '家具', 'スポーツ']),
  "price": zod.number().describe('価格（円）'),
  "inStock": zod.boolean(),
  "description": zod.string(),
  "rating": zod.number().min(getProductByIdResponseRatingMin).max(getProductByIdResponseRatingMax),
  "reviews": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.string(),
  "rating": zod.number().min(1).max(getProductByIdResponseReviewsItemRatingMax),
  "comment": zod.string()
}))
})
