/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */
import { customAxiosInstance } from '../plugins/axios';
export interface MenuChild {
  label: string;
  to: string;
  icon?: string;
}

export interface MenuItem {
  id: string;
  label: string;
  icon: string;
  children: MenuChild[];
}

export type ProductCategory = typeof ProductCategory[keyof typeof ProductCategory];


export const ProductCategory = {
  食品: '食品',
  電子機器: '電子機器',
  ファッション: 'ファッション',
  家具: '家具',
  スポーツ: 'スポーツ',
} as const;

export interface Review {
  id: number;
  author: string;
  /**
     * @minimum 1
     * @maximum 5
     */
  rating: number;
  comment: string;
}

export interface Product {
  id: number;
  name: string;
  category: ProductCategory;
  /** 価格（円） */
  price: number;
  inStock: boolean;
  description: string;
  /**
     * @minimum 0
     * @maximum 5
     */
  rating: number;
  reviews: Review[];
}

export interface ProductListResponse {
  items: Product[];
  /** フィルタ後の総件数 */
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface ErrorResponse {
  message: string;
}

export type GetProductsParams = {
/**
 * キーワード検索（name・description を対象）
 */
q?: string;
/**
 * カテゴリフィルタ
 */
category?: ProductCategory;
/**
 * 在庫ありのみ
 */
inStock?: boolean;
/**
 * ページ番号（1始まり）
 * @minimum 1
 */
page?: number;
/**
 * 1ページあたりの件数
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAppAPI = () => {
/**
 * @summary メインメニュー取得
 */
const getMenu = (

 options?: SecondParameter<typeof customAxiosInstance<MenuItem[]>>,) => {
      return customAxiosInstance<MenuItem[]>(
      {url: `/menu`, method: 'GET'
    },
      options);
    }

/**
 * @summary 商品一覧取得
 */
const getProducts = (
    params?: GetProductsParams,
 options?: SecondParameter<typeof customAxiosInstance<ProductListResponse>>,) => {
      return customAxiosInstance<ProductListResponse>(
      {url: `/products`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary 商品詳細取得
 */
const getProductById = (
    id: number,
 options?: SecondParameter<typeof customAxiosInstance<Product>>,) => {
      return customAxiosInstance<Product>(
      {url: `/products/${id}`, method: 'GET'
    },
      options);
    }

return {getMenu,getProducts,getProductById}};
export type GetMenuResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAppAPI>['getMenu']>>>
export type GetProductsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAppAPI>['getProducts']>>>
export type GetProductByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAppAPI>['getProductById']>>>
