/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Products API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import { customAxiosInstance } from '../plugins/axios';
export type ProductCategory = typeof ProductCategory[keyof typeof ProductCategory];


export const ProductCategory = {
  食品: '食品',
  電子機器: '電子機器',
  ファッション: 'ファッション',
  家具: '家具',
  スポーツ: 'スポーツ',
} as const;

export interface Review {
  id: number;
  author: string;
  /**
     * @minimum 1
     * @maximum 5
     */
  rating: number;
  comment: string;
}

export interface Product {
  id: number;
  name: string;
  category: ProductCategory;
  /** 価格（円） */
  price: number;
  inStock: boolean;
  description: string;
  /**
     * @minimum 0
     * @maximum 5
     */
  rating: number;
  reviews: Review[];
}

export interface ProductListResponse {
  items: Product[];
  /** フィルタ後の総件数 */
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface ErrorResponse {
  message: string;
}

export type GetProductsParams = {
/**
 * キーワード検索（name・description を対象）
 */
q?: string;
/**
 * カテゴリフィルタ
 */
category?: ProductCategory;
/**
 * 在庫ありのみ
 */
inStock?: boolean;
/**
 * ページ番号（1始まり）
 * @minimum 1
 */
page?: number;
/**
 * 1ページあたりの件数
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};

export type getProductsResponse200 = {
  data: ProductListResponse
  status: 200
}

export type getProductsResponseSuccess = (getProductsResponse200) & {
  headers: Headers;
};
;

export type getProductsResponse = (getProductsResponseSuccess)

export const getGetProductsUrl = (params?: GetProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/products?${stringifiedParams}` : `/products`
}

/**
 * @summary 商品一覧取得
 */
export const getProducts = async (params?: GetProductsParams, options?: RequestInit): Promise<getProductsResponse> => {

  return customAxiosInstance<getProductsResponse>(getGetProductsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProductsQueryKey = (params?: MaybeRef<GetProductsParams>,) => {
    return [
    'products', ...(params ? [params] : [])
    ] as const;
    }


export const getGetProductsQueryOptions = <TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(params?: MaybeRef<GetProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetProductsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({ signal }) => getProducts(unref(params), { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>
}

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>
export type GetProductsQueryError = unknown


/**
 * @summary 商品一覧取得
 */

export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: MaybeRef<GetProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type getProductByIdResponse200 = {
  data: Product
  status: 200
}

export type getProductByIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getProductByIdResponseSuccess = (getProductByIdResponse200) & {
  headers: Headers;
};
export type getProductByIdResponseError = (getProductByIdResponse404) & {
  headers: Headers;
};

export type getProductByIdResponse = (getProductByIdResponseSuccess | getProductByIdResponseError)

export const getGetProductByIdUrl = (id: number,) => {




  return `/products/${id}`
}

/**
 * @summary 商品詳細取得
 */
export const getProductById = async (id: number, options?: RequestInit): Promise<getProductByIdResponse> => {

  return customAxiosInstance<getProductByIdResponse>(getGetProductByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProductByIdQueryKey = (id: MaybeRef<number>,) => {
    return [
    'products',id
    ] as const;
    }


export const getGetProductByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductById>>, TError = ErrorResponse>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetProductByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductById>>> = ({ signal }) => getProductById(unref(id), { signal });





   return  { queryKey, queryFn, enabled: computed(() => unref(id) !== null && unref(id) !== undefined), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>
}

export type GetProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>
export type GetProductByIdQueryError = ErrorResponse


/**
 * @summary 商品詳細取得
 */

export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = ErrorResponse>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
