/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCategory } from './productCategory';

export type GetProductsParams = {
/**
 * キーワード検索（name・description を対象）
 */
q?: string;
/**
 * カテゴリフィルタ
 */
category?: ProductCategory;
/**
 * 在庫ありのみ
 */
inStock?: boolean;
/**
 * ページ番号（1始まり）
 * @minimum 1
 */
page?: number;
/**
 * 1ページあたりの件数
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};
