/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */
import type { MenuChild } from './menuChild';

export interface MenuItem {
  id: string;
  label: string;
  icon: string;
  children: MenuChild[];
}
