/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */

export type ProductCategory = typeof ProductCategory[keyof typeof ProductCategory];


export const ProductCategory = {
  食品: '食品',
  電子機器: '電子機器',
  ファッション: 'ファッション',
  家具: '家具',
  スポーツ: 'スポーツ',
} as const;
