/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */
import type { Product } from './product';

export interface ProductListResponse {
  items: Product[];
  /** フィルタ後の総件数 */
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
