/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */

export interface Review {
  id: number;
  author: string;
  /**
     * @minimum 1
     * @maximum 5
     */
  rating: number;
  comment: string;
}
