/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * App API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCategory } from './productCategory';

/**
 * 在庫検索画面専用の検索条件（画面固有オブジェクトのお手本。プロパティ構成は画面ごとに自由に定義する）
 */
export interface StockSearchCondition {
  /** キーワード（複数指定時は OR。name・description を対象） */
  keywords?: string[];
  /** カテゴリ（複数指定時は OR） */
  categories?: ProductCategory[];
  /** 在庫ありのみに絞り込む */
  inStockOnly?: boolean;
}
